### ISSUE TITLE
Instinct Unfriendliness: Plants and Foods

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#1]
A lot of the plants and foods have been reported to be instinct-unfriendly! If you have any more details about exactly what is unfriendly and why/how, please include details here. Exact classifiers and scripts are especially appreciated. This might eventually be broken out into separate issues if needed.

**Comment by the1whoscreamsiguess** [comment]
-Creatures can see and attempt to eat unripe nuts, tomatoes, triffid fruits, and trumpet fruits, as well as several patch fruits that grow too high up for creatures to reach.
-Creatures can see ripe pears on the plant, but they only become edible when manually picked.
-Creatures can see half-eaten tomatoes and cannot eat them. They [i]can[/i] eat half-eaten nuts, rapidly driving them to extinction. Both types of fruit should become invisible after the first bite to prevent confusion and ensure survival.
-Deathcap mushrooms are invisible to creatures and do not function as a hazard. Their spores are classed "seed" and are visible to creatures, but they cannot be eaten. 
-The honey hive in the garden functions as a dispenser but is a "nest" and shares a classifier with the beehives. (???????)
-The toxic purple berries on the bridge emit protein smell, potentially confusing creature navigation. They are classed "bad", a classification only used by C3's hot lava rocks and the Yule Pack fireworks.
-The coconuts on the left side of the volcano are classed "seed" and emit carb smell, but they can only be pushed or hit to crack them open, producing bits classed "fruit". They would benefit from being reclassed to toys and having a "played with toy" stimulus added.
-Both types of cacti as well as those weird lumpy weed things cannot be interacted with by creatures.
-Several food items contain unnecessary empty hunger decreases.

**Comment by Amaikokonut** [comment]
Closing since these all seem to pass the (automated and imperfect) instinct friendliness tests now, but if any issues persist we can open them per-agent.
