### ISSUE TITLE
Creatures Development Standards: Critters and Bugs

### ISSUE THREAD

**Issue by JennaMalkin** [Creatures-Developer-Network/C2toDS-Refresh#10]
All critters and bugs should be pushable, pullable, hittable and edible, with appropriate stimuli.  

See the https://creatures.wiki/Creatures_Development_Standards for more details on this.

**Comment by Amaikokonut** [comment]
Closing this because all critters and bugs (I think) either met these standards now, or in some cases are simply invisible to creatures.

If further issues arise, we can open issues for those agents individually.
