### ISSUE TITLE
Creatures fill the incubator with junk over time

### ISSUE THREAD

**Issue by the1whoscreamsiguess** [Creatures-Developer-Network/C2toDS-Refresh#100]
Creatures can drop objects into the incubator but cannot see them to get them back out. This especially happens with tomatoes, which do not decay while in a container and will slowly accumulate as long as there are creatures living near the incubator.

**Comment by NeoDement** [comment]
#98 attempts to fix this by adding the Open Air Cabin attribute to the Incubator and allowing Tomatoes to decay and die inside vehicles. Nuts Pears etc will probably need the same fix.
