### ISSUE TITLE
Clickable Overlays

### ISSUE THREAD

**Issue by babyblueboxers** [Creatures-Developer-Network/C2toDS-Refresh#129]
This world overlay is clickable for some reason? All overlay attributes should be checked for click-ability.

![image](https://github.com/Creatures-Developer-Network/C2toDS-Refresh/assets/18275780/b4cedd97-9dff-4775-9d5b-c5346cc9851a)

**Comment by NeoDement** [comment]
the reason for this is a special script runs that redirects the pointer click 1 pixel to the left, if you click any overlay using dither transparency. this makes interacting with objects inside of pipes etc a lot more consistent. previous behaviour would have the pointer do nothing with no clear feedback to the user.

![engine_ajbXCO1Ekw](https://github.com/user-attachments/assets/84f67a16-2424-404c-83a6-5ec3b3fa650d)

maybe the script could be improved to not play the click animation if the click lands directly on the overlay.****
