### ISSUE TITLE
Bat Errors

### ISSUE THREAD

**Issue by JennaMalkin** [Creatures-Developer-Network/C2toDS-Refresh#16]
For whatever reason, in my game, this area with the bats is causing a lot of problems.  

![baterror](https://user-images.githubusercontent.com/5298344/122672138-5789f980-d20d-11eb-9122-3111a8b1d266.PNG)

Runtime error in agent 2 16 50203 script 2 16 50203 9 unique id 2548 
Invalid agent
 ...  0 -5 gsub eat drop {@}mesg writ ov08 12 gsub wakeup  ... 

Runtime error in agent 2 10 50204 script 2 10 50204 10 unique id 27102 
ATTR/PERM change caused invalid map position (0.000000)
 ... c 50 aero 4 bhvr 48 {@}perm 51 tick rand 500 700 puhl ... 

Runtime error in agent 2 16 50203 script 2 16 50203 9 unique id 2548 
Invalid TARG
 ... stop endi targ ov08 {@}setv va00 bhvr andv va00 48 do ...

**Comment by Amaikokonut** [comment]
For reference: The first and third are bat-related, the middle one is pear detritus

**Comment by JennaMalkin** [comment]
Runtime error in agent 2 16 50203 script 2 16 50203 9 unique id 2213 
Invalid agent
 ... va02 eq 0 targ va04 {@}setv va01 relx ownr targ setv  ...

**Comment by bedalton** [comment]
```
Runtime error in agent 2 16 50203 script 2 16 50203 9 unique id 138637 
Invalid TARG
 ... ll and targ ne ownr {@}doif carr eq null setv va00 bh ... 
```

Another Bat error
Not sure why this one occurs though. Agent is checked for not null right before

https://github.com/Creatures-Developer-Network/C2toDS-Refresh/blob/02ddf56ff5d6f88b1cf2d6afe767e227eec3ab5b/dev/Scripts/2.2_Bats.cos#L313-L317

**Comment by Amaikokonut** [comment]
I'll have to check if it's the case here. but usually those targ errors happen when the checking-for-null bits of the script aren't run in an INST along with the lines manipulating the object. It's uncommon but still quite possible for an agent to disappear between ticks.

**Comment by bedalton** [comment]
Agent going invalid during the script seemed to be the case. I added INST statements to the scripts before null-checks and it seems okay so far. Haven't had an error on bats since I started this world 4 hours ago.

I plan to run the game through the night and see if any errors occur. If not I will submit the fix for testing.
