### ISSUE TITLE
Heritage Caterpillar MVSF Error

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#24]
![image](https://user-images.githubusercontent.com/34694450/122779680-17159480-d27c-11eb-9c11-b26a7ce31a8a.png)
My guess is a creature was holding the caterpillar at the time.

**Comment by Amaikokonut** [comment]
I added some empty pickup scripts in #18 in hopes that creatures grabbing them would interrupt the timer scripts that are trying to mvsf them, and there's a check at the beginning of the timer script to not run if being held, but I am pretty sure I have still seen this error at least once since making these changes, so I'm not closing it yet.

**Comment by JennaMalkin** [comment]
I've also seen this error in the Red Caterpillar and the Purple Caterpillar.

**Comment by Vermidia** [comment]
Checking MOVS might help, as well as having the mvsf part be inst.

**Comment by Amaikokonut** [comment]
fixed theoretically in #70, will reopen if we see this again.
