### ISSUE TITLE
Pear Seed Invalid Map Position Error

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#26]
![image](https://user-images.githubusercontent.com/34694450/122808379-d6794380-d29a-11eb-80b8-d34fbfbb9027.png)

**Comment by JennaMalkin** [comment]
Runtime error in agent 2 3 50204 script 2 3 50204 9 unique id 176001 
Invalid map position (3558.406982, 48226.558594)
 ...  else show 0 bhvr 0 {@}attr 209 endi retn subr grow s ...

**Comment by Amaikokonut** [comment]
#26 should fix this but reopen the issue if shows up again with the new files.

**Comment by bedalton** [comment]
I still had the error occur with this fix. MVSF fails when the seed is too far off the map. 
````
 Runtime error in agent 2 3 50204 script 2 3 50204 9 unique id 1643982 
Failed to find safe location (12924.807617, 23690526.000000)
 ... tmvt posl post eq 0 {@}mvsf posl post endi attr 209 s ..
````



Replacing MVSF with  `kill targ` prevents the move safe failure, and I think would make the off map seed handling more predictable.
