### ISSUE TITLE
Incubator Invalid TARG

### ISSUE THREAD

**Issue by JennaMalkin** [Creatures-Developer-Network/C2toDS-Refresh#28]
Runtime error in agent 2 22 50200 script 2 22 50200 9 unique id 2675 
Invalid TARG
 ... v va99 0 enum 4 0 0 {@}doif dead = 0 addv va99 1 endi ... 

NB. May already be fixed by this: https://github.com/Creatures-Developer-Network/C2toDS-Refresh/blob/main/dev/Scripts/1.3_Incubator.cos

**Comment by Amaikokonut** [comment]
Hmmm, yeah, that error should be fixed, but if you get it again while running the updated scripts feel free to reopen the issue!
