### ISSUE TITLE
Pear Plant Duplicate Part Error

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#33]
![image](https://user-images.githubusercontent.com/34694450/123084445-1f421100-d3ef-11eb-9da2-0dd3df36bc89.png)

**Comment by bedalton** [comment]
I could not figure out what caused this error, but I received it a number of times. I added a lock/unlk statement around pear parts creation, and have not had the error since. 

Still needs testing for this, though a rewrite was suggested.

**Comment by Amaikokonut** [comment]
![image](https://user-images.githubusercontent.com/34694450/161403735-b279b9ef-520e-476f-aba1-5b698be2ac68.png)
This is still happening occasionally
