### ISSUE TITLE
Pear Incompatible Type Error

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#34]
![image](https://user-images.githubusercontent.com/34694450/123090380-0db03780-d3f6-11eb-8468-a2e7f7227561.png)

**Comment by bedalton** [comment]
This error is thrown from the error catching script. 

I wonder if the error has anything to do with the fact that the script checks if ov04, ov05 and ov06 are null, but their values are not initialized to null on creation, and depending on when the original error is thrown, the variables may have never been initialized to any agent value, meaning they are still set to an integer value.

**Comment by Amaikokonut** [comment]
I was looking at over the pear scripts a while ago and I think that's exactly it. The entire pear script seems strangely over-complicated for what it is, which lends itself to all sorts of errors. It would benefit from either a rewrite or at least a good thorough teardown/detailed annotation to start.

**Comment by bedalton** [comment]
Setting mv[4-6] to null in constructor seems to have prevent this error so far.

**Comment by Amaikokonut** [comment]
wonderful! I'll close this, just reopen it if it happens again.
