### ISSUE TITLE
Trumpet Plant Fix?

### ISSUE THREAD

**Issue by JennaMalkin** [Creatures-Developer-Network/C2toDS-Refresh#38]
Could the trumpet plant be fixed like Jabber's C2 Trumpet Plant Fix?  

https://creaturescaves.com/downloads.php?section=COBs&view=1953

**Comment by bedalton** [comment]
I have spent a good deal of time watching the trumpet plants. I have modified the script so they live three days and give three sets of seeds, I also try to make the seeds last through winter. 

With those problems taken care of more or less, there are two other problems that are harder to address. 

1. Birds eat a bunch of the seeds
2. The plants move more and more to the right over time

The biggest problem is the seeds almost always floating right.  This moves the plant population more and more to the right until all seeds are landing on the bridge and platform above, and the plant goes extinct

**Comment by bedalton** [comment]
This line seems to be the culprit for the floating right. Changed it to 2 and -2 and the seeds now float in either direction

https://github.com/Creatures-Developer-Network/C2toDS-Refresh/blob/6e70325f863d851dd22520d99fba54c4bec82991/dev/Scripts/2.0_Trumpet.cos#L224

**Comment by JennaMalkin** [comment]
@bedalton , are you going to push your fix to the trumpet plants to the repository?

**Comment by bedalton** [comment]
I can submit a fix for that one line, but I am still working on making the trumpet plant population stable over time. I have made some improvements, but the plant population does not survive more than 2 years.
