### ISSUE TITLE
Clouds Error - Repeat is Less Than One

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#48]
Well... this is a new one.

![image](https://user-images.githubusercontent.com/34694450/124674613-12123100-de89-11eb-882e-f9fe40a6293a.png)

**Comment by Vermidia** [comment]
`setv va08 obst down

		divv va08 80

		doif va08 le 0 or va08 ge 30

			setv va08 3

		endi

*scare creatures

		esee 4 0 0

			chem 158 .5

		next

		targ ownr



		doif va08 gt 0`
Is everything that comes before...
There's a chance that va08 is counted as a float and when passed into reps as an int becomes 0 when truncated, otherwise idk how??

**Comment by Vermidia** [comment]
It seems obst does return a float!, Will make a modification to the doif va08 le 0 to lt 1 to hopefully fix this rare issue.

**Comment by Amaikokonut** [comment]
CAOS, you strange, strange creature.

**Comment by Amaikokonut** [comment]
Fixed nearly immediately by #49 :D
