### ISSUE TITLE
Creatures Miss The Yellow Boat

### ISSUE THREAD

**Issue by Amaikokonut** [Creatures-Developer-Network/C2toDS-Refresh#8]
According to reports, sometimes creatures walk off the edge of the dock and miss the yellow boat, falling right into the sea! That's a little unfair.

**Comment by Vermidia** [comment]
Since the yellow boat should now be controlled by the boat call buttons, this is hopefully fixed, as they can no longer interact with the boat itself.

**Comment by Amaikokonut** [comment]
I believe this issue is referring to this particular oddity, where you'd think the norn would run into the boat, and then it just falls through it:
![Peek norn runs away](https://user-images.githubusercontent.com/34694450/122781243-9ce60f80-d27d-11eb-92d3-8a7db4014400.gif)
We should probably just make those edges un-walk-offable, huh?

**Comment by Amaikokonut** [comment]
Hooray!

![catchraft](https://user-images.githubusercontent.com/34694450/161404984-62a5e6d2-6fc3-48e7-9e63-68a1e67e11fe.gif)
