### ISSUE TITLE
Call button hit script?

### ISSUE THREAD

**Issue by JennaMalkin** [Creatures-Developer-Network/C2toDS-Refresh#90]
The Creatures Development Standards currently recommend a hit script in addition to the push and pull scripts.  Should a hit script for a call button act the same way as the push and pull? (i.e. does it call the lift?)

**Comment by JennaMalkin** [comment]
Consider having the call button hit script:
a) NOT call the lift.
b) stimulate with 92 - I have hit machine
c) blink-blink-blink the call button light on and off again
d) make some sort of appropriate sound

**Comment by Amaikokonut** [comment]
addressed by #91
